"""
train.py — distill tabular Leduc blueprint into a policy NN.

Loads JSONL training data (288 records, one per Leduc infoset) generated by
the Go cmd/dump-training-data tool. Trains a small MLP (35 → 64 → 32 → 3) with
KL-style cross-entropy distillation, masking illegal actions.

Usage:
    python3 distill/train.py \
        --data distill/data/leduc-train.jsonl \
        --out distill/models/leduc-policy.pt \
        --epochs 300 --lr 1e-3

POC criteria (Week 2 README):
    NN ↔ tabular KL < 0.05
"""

import argparse
import json
import os
import sys
import time
from typing import List

try:
    import numpy as np
    import torch
    import torch.nn as nn
    import torch.nn.functional as F
except ImportError as e:
    sys.exit(
        f"[train] missing dependency: {e}\n"
        f"        pip3 install -r distill/requirements.txt"
    )

DEFAULT_NUM_ACTIONS = 3  # Leduc / HUNL push/fold; multi-street NLHE uses 6.


class PolicyMLP(nn.Module):
    """Compact MLP for distilling game blueprints.
    Feature dim configured per dataset (Leduc=35, push/fold=33, multi-street=134).
    Num actions also per dataset (3 or 6)."""

    def __init__(self, feature_dim: int, hidden=(64, 32), num_actions: int = DEFAULT_NUM_ACTIONS):
        super().__init__()
        layers: List[nn.Module] = []
        prev = feature_dim
        for h in hidden:
            layers += [nn.Linear(prev, h), nn.ReLU()]
            prev = h
        layers.append(nn.Linear(prev, num_actions))
        self.net = nn.Sequential(*layers)

    def forward(self, features: torch.Tensor) -> torch.Tensor:
        """Returns raw logits (legal-mask applied by caller)."""
        return self.net(features)


def load_jsonl(path: str):
    feats, probs, masks, labels = [], [], [], []
    with open(path) as f:
        for line in f:
            r = json.loads(line)
            feats.append(r["features"])
            probs.append(r["probs"])
            masks.append(r["legal"])
            labels.append(r.get("label", ""))  # optional (multi-street dump omits)
    return (
        torch.tensor(feats, dtype=torch.float32),
        torch.tensor(probs, dtype=torch.float32),
        torch.tensor(masks, dtype=torch.float32),
        labels,
    )


def masked_kl(logits: torch.Tensor, target_probs: torch.Tensor, legal_mask: torch.Tensor) -> torch.Tensor:
    """KL(target || NN) after masking illegal actions in NN output."""
    # Mask logits: -inf where illegal so softmax → 0.
    very_neg = torch.full_like(logits, -1e9)
    masked_logits = torch.where(legal_mask > 0, logits, very_neg)
    log_q = F.log_softmax(masked_logits, dim=-1)
    # KL(P||Q) = Σ P log P - Σ P log Q. Ignore the P log P (constant w.r.t. params).
    return -(target_probs * log_q).sum(dim=-1).mean()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", default="distill/data/leduc-train.jsonl")
    ap.add_argument("--out", default="distill/models/leduc-policy.pt")
    ap.add_argument("--epochs", type=int, default=2000)
    ap.add_argument("--lr", type=float, default=3e-3)
    ap.add_argument("--batch", type=int, default=64)
    ap.add_argument("--val-frac", type=float, default=0.0,
                    help="0 = train on all data (recommended for distillation). >0 = split for early stopping.")
    ap.add_argument("--hidden", type=int, nargs="+", default=[128, 64],
                    help="hidden layer sizes")
    ap.add_argument("--num-actions", type=int, default=DEFAULT_NUM_ACTIONS,
                    help="output action dim (3 for push/fold, 6 for multi-street)")
    ap.add_argument("--seed", type=int, default=42)
    args = ap.parse_args()

    torch.manual_seed(args.seed)
    np.random.seed(args.seed)

    print(f"[train] loading {args.data}")
    feats, probs, masks, labels = load_jsonl(args.data)
    n = feats.shape[0]
    feature_dim = feats.shape[1]
    print(f"[train] N={n}  feature_dim={feature_dim}  num_actions={probs.shape[1]}")
    assert probs.shape[1] == args.num_actions, f"data num_actions={probs.shape[1]} != --num-actions={args.num_actions}"

    # Train/val split — for distillation default is val_frac=0 (use all 288 infosets).
    idx = torch.randperm(n)
    n_val = int(n * args.val_frac)
    val_idx, tr_idx = idx[:n_val], idx[n_val:]
    print(f"[train] split: train={len(tr_idx)}  val={len(val_idx)}")

    model = PolicyMLP(feature_dim=feature_dim, hidden=tuple(args.hidden), num_actions=args.num_actions)
    print(f"[train] model: {sum(p.numel() for p in model.parameters())} params  hidden={args.hidden}  num_actions={args.num_actions}")
    opt = torch.optim.Adam(model.parameters(), lr=args.lr)

    best_metric = float("inf")
    best_state = None
    t0 = time.time()
    for epoch in range(1, args.epochs + 1):
        model.train()
        perm = torch.randperm(len(tr_idx))
        epoch_loss = 0.0
        for i in range(0, len(tr_idx), args.batch):
            b = tr_idx[perm[i : i + args.batch]]
            logits = model(feats[b])
            loss = masked_kl(logits, probs[b], masks[b])
            opt.zero_grad()
            loss.backward()
            opt.step()
            epoch_loss += loss.item() * len(b)
        epoch_loss /= len(tr_idx)

        # Eval — val if split, else train loss as proxy.
        model.eval()
        with torch.no_grad():
            if len(val_idx) > 0:
                val_logits = model(feats[val_idx])
                metric = masked_kl(val_logits, probs[val_idx], masks[val_idx]).item()
                metric_name = "val_loss"
            else:
                # Pure distillation: track full-train CE as the optimization target.
                full_logits = model(feats)
                metric = masked_kl(full_logits, probs, masks).item()
                metric_name = "full_ce"

        if metric < best_metric:
            best_metric = metric
            best_state = {k: v.clone() for k, v in model.state_dict().items()}

        if epoch <= 5 or epoch % 100 == 0 or epoch == args.epochs:
            print(f"[train] epoch {epoch:5d}/{args.epochs}  tr_loss={epoch_loss:.6f}  {metric_name}={metric:.6f}  best={best_metric:.6f}")

    print(f"[train] done in {time.time()-t0:.1f}s, best {metric_name}={best_metric:.6f}")
    if best_state is None:
        sys.exit("[train] no best state captured")
    model.load_state_dict(best_state)

    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    torch.save({
        "state_dict": model.state_dict(),
        "feature_dim": feature_dim,
        "num_actions": args.num_actions,
        "hidden": list(args.hidden),
    }, args.out)
    print(f"[train] saved {args.out}")

    # Quick KL report across full dataset. KL = CE - target_entropy (the
    # irreducible part of CE comes from target's own entropy; for mixed-strategy
    # Nash this is non-negligible, ~1.0 nats).
    model.eval()
    with torch.no_grad():
        all_logits = model(feats)
        all_ce = masked_kl(all_logits, probs, masks).item()
        # Target entropy per-sample, ignoring zero-prob terms (numerical safety).
        eps = 1e-12
        log_probs = torch.log(probs.clamp(min=eps))
        target_ent = -(probs * log_probs).sum(dim=-1).mean().item()
        kl = all_ce - target_ent
    print(f"[train] FULL-DATASET masked CE = {all_ce:.6f}")
    print(f"[train] FULL-DATASET target entropy = {target_ent:.6f}")
    print(f"[train] FULL-DATASET KL(target || NN) = {kl:.6f}  (POC threshold < 0.05)")


if __name__ == "__main__":
    main()
